import { MeasureType } from "@/types/measures";

interface HospitalMeasurement {
  patientSurveyStarRating: number | undefined;
  hcahpsAnswerPercent: number | undefined;
  hcahpsLinearMeanValue: number | undefined;
}

//TODO: use this for knowing what filter control to show
export const measurePropertyMap: Record<MeasureType, keyof HospitalMeasurement> = {
  H_COMP_1_A_P: "hcahpsAnswerPercent",
  H_COMP_1_SN_P: "hcahpsAnswerPercent",
  H_COMP_1_U_P: "hcahpsAnswerPercent",
  H_COMP_1_LINEAR_SCORE: "hcahpsLinearMeanValue",
  H_COMP_1_STAR_RATING: "patientSurveyStarRating",
  H_NURSE_RESPECT_A_P: "hcahpsAnswerPercent",
  H_NURSE_RESPECT_SN_P: "hcahpsAnswerPercent",
  H_NURSE_RESPECT_U_P: "hcahpsAnswerPercent",
  H_NURSE_LISTEN_A_P: "hcahpsAnswerPercent",
  H_NURSE_LISTEN_SN_P: "hcahpsAnswerPercent",
  H_NURSE_LISTEN_U_P: "hcahpsAnswerPercent",
  H_NURSE_EXPLAIN_A_P: "hcahpsAnswerPercent",
  H_NURSE_EXPLAIN_SN_P: "hcahpsAnswerPercent",
  H_NURSE_EXPLAIN_U_P: "hcahpsAnswerPercent",
  H_COMP_2_A_P: "hcahpsAnswerPercent",
  H_COMP_2_SN_P: "hcahpsAnswerPercent",
  H_COMP_2_U_P: "hcahpsAnswerPercent",
  H_COMP_2_LINEAR_SCORE: "hcahpsLinearMeanValue",
  H_COMP_2_STAR_RATING: "patientSurveyStarRating",
  H_DOCTOR_RESPECT_A_P: "hcahpsAnswerPercent",
  H_DOCTOR_RESPECT_SN_P: "hcahpsAnswerPercent",
  H_DOCTOR_RESPECT_U_P: "hcahpsAnswerPercent",
  H_DOCTOR_LISTEN_A_P: "hcahpsAnswerPercent",
  H_DOCTOR_LISTEN_SN_P: "hcahpsAnswerPercent",
  H_DOCTOR_LISTEN_U_P: "hcahpsAnswerPercent",
  H_DOCTOR_EXPLAIN_A_P: "hcahpsAnswerPercent",
  H_DOCTOR_EXPLAIN_SN_P: "hcahpsAnswerPercent",
  H_DOCTOR_EXPLAIN_U_P: "hcahpsAnswerPercent",
  H_COMP_3_A_P: "hcahpsAnswerPercent",
  H_COMP_3_SN_P: "hcahpsAnswerPercent",
  H_COMP_3_U_P: "hcahpsAnswerPercent",
  H_COMP_3_LINEAR_SCORE: "hcahpsLinearMeanValue",
  H_COMP_3_STAR_RATING: "patientSurveyStarRating",
  H_CALL_BUTTON_A_P: "hcahpsAnswerPercent",
  H_CALL_BUTTON_SN_P: "hcahpsAnswerPercent",
  H_CALL_BUTTON_U_P: "hcahpsAnswerPercent",
  H_BATH_HELP_A_P: "hcahpsAnswerPercent",
  H_BATH_HELP_SN_P: "hcahpsAnswerPercent",
  H_BATH_HELP_U_P: "hcahpsAnswerPercent",
  H_COMP_5_A_P: "hcahpsAnswerPercent",
  H_COMP_5_SN_P: "hcahpsAnswerPercent",
  H_COMP_5_U_P: "hcahpsAnswerPercent",
  H_COMP_5_LINEAR_SCORE: "hcahpsLinearMeanValue",
  H_COMP_5_STAR_RATING: "patientSurveyStarRating",
  H_MED_FOR_A_P: "hcahpsAnswerPercent",
  H_MED_FOR_SN_P: "hcahpsAnswerPercent",
  H_MED_FOR_U_P: "hcahpsAnswerPercent",
  H_SIDE_EFFECTS_A_P: "hcahpsAnswerPercent",
  H_SIDE_EFFECTS_SN_P: "hcahpsAnswerPercent",
  H_SIDE_EFFECTS_U_P: "hcahpsAnswerPercent",
  H_COMP_6_N_P: "hcahpsAnswerPercent",
  H_COMP_6_Y_P: "hcahpsAnswerPercent",
  H_COMP_6_LINEAR_SCORE: "hcahpsLinearMeanValue",
  H_COMP_6_STAR_RATING: "patientSurveyStarRating",
  H_DISCH_HELP_N_P: "hcahpsAnswerPercent",
  H_DISCH_HELP_Y_P: "hcahpsAnswerPercent",
  H_SYMPTOMS_N_P: "hcahpsAnswerPercent",
  H_SYMPTOMS_Y_P: "hcahpsAnswerPercent",
  H_COMP_7_A: "hcahpsAnswerPercent",
  H_COMP_7_D_SD: "hcahpsAnswerPercent",
  H_COMP_7_SA: "hcahpsAnswerPercent",
  H_COMP_7_LINEAR_SCORE: "hcahpsLinearMeanValue",
  H_COMP_7_STAR_RATING: "patientSurveyStarRating",
  H_CT_PREFER_A: "hcahpsAnswerPercent",
  H_CT_PREFER_D_SD: "hcahpsAnswerPercent",
  H_CT_PREFER_SA: "hcahpsAnswerPercent",
  H_CT_UNDER_A: "hcahpsAnswerPercent",
  H_CT_UNDER_D_SD: "hcahpsAnswerPercent",
  H_CT_UNDER_SA: "hcahpsAnswerPercent",
  H_CT_MED_A: "hcahpsAnswerPercent",
  H_CT_MED_D_SD: "hcahpsAnswerPercent",
  H_CT_MED_SA: "hcahpsAnswerPercent",
  H_CLEAN_HSP_A_P: "hcahpsAnswerPercent",
  H_CLEAN_HSP_SN_P: "hcahpsAnswerPercent",
  H_CLEAN_HSP_U_P: "hcahpsAnswerPercent",
  H_CLEAN_LINEAR_SCORE: "hcahpsLinearMeanValue",
  H_CLEAN_STAR_RATING: "patientSurveyStarRating",
  H_QUIET_HSP_A_P: "hcahpsAnswerPercent",
  H_QUIET_HSP_SN_P: "hcahpsAnswerPercent",
  H_QUIET_HSP_U_P: "hcahpsAnswerPercent",
  H_QUIET_LINEAR_SCORE: "hcahpsLinearMeanValue",
  H_QUIET_STAR_RATING: "patientSurveyStarRating",
  H_HSP_RATING_0_6: "hcahpsAnswerPercent",
  H_HSP_RATING_7_8: "hcahpsAnswerPercent",
  H_HSP_RATING_9_10: "hcahpsAnswerPercent",
  H_HSP_RATING_LINEAR_SCORE: "hcahpsLinearMeanValue",
  H_HSP_RATING_STAR_RATING: "patientSurveyStarRating",
  H_RECMND_DN: "hcahpsAnswerPercent",
  H_RECMND_DY: "hcahpsAnswerPercent",
  H_RECMND_PY: "hcahpsAnswerPercent",
  H_RECMND_LINEAR_SCORE: "hcahpsLinearMeanValue",
  H_RECMND_STAR_RATING: "patientSurveyStarRating",
  H_STAR_RATING: "patientSurveyStarRating"
};
